apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: calculateapi
spec:
  completions: 20
  parallelism: 5
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - perl
        - -Mbigum
        - -wle
        - print bpi(200)
        image: perl:5.34.0
        name: calculateapi
        resources: {}
      restartPolicy: Never
status: {}
